#:import ColorHex kivy.utils.get_color_from_hex

<FBranco@FloatLayout>:
    size_hint: .3, .3
    canvas.before: 
        Color:
            rgba: ColorHex('#00FF00')
        Rectangle:
            pos: self.pos
            size: self.size
    Button:
        size_hint: .3, .3
        pos_hint: {'center_x': .5, 'center_y': .5}
        text: 'Color'
        background_color: ColorHex('#FF0000')
        background_normal: ''

FBranco: